title: Alan Turing Challenges
description: Esse mini-blog é uma compilação de estudos de algoritmos e matemática para computação, focado em competições.
github_username:  turing-challenges

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
